---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-production-tls
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  secretName: home-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.home.techfitsu.org"
  dnsNames:
  - "*.home.techfitsu.org"
