---
version: "3.7"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - MENU_VERSION=2.0.76 # optional
      - TZ=America/Chicago
    volumes:
      - netbootxyz_config:/config # optional
      - netbootxyz_assets:/assets # optional
    ports:
      - 3000:3000
      - 69:69/udp
    restart: always
    
    labels:
      - traefik.enable=true
      - traefik.http.routers.netbootxyz.entrypoints=websecure
      - traefik.http.routers.netbootxyz.rule=Host(`netbootxyz.home.techfitsu.org`)
      - traefik.http.routers.netbootxyz.tls=true
      - traefik.http.routers.netbootxyz.tls.certresolver=production
      - traefik.http.services.netbootxyz.loadbalancer.server.port=3000

    networks:
      - traefik_default

volumes:
  netbootxyz_config:
  netbootxyz_assets:

networks:
  traefik_default:
    external: true