version: "3.7"

services:
  traefik:
    container_name: traefik
    image: "traefik:latest"    
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # UI for Traefik web dashboard [optional]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./config:/etc/traefik"
      - "traefik_data:/data/traefik"
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - traefik_default
    # environment:
    #   - CF_DNS_API_TOKEN=YOUR_API_TOKEN
    #   If you choose to use an API Key instead of a Token, specify your email as well
    #   - CF_API_EMAIL=user@example.com
    #   - CF_API_KEY=YOUR_API_KEY
    env_file:
      - traefik.env
    restart: always

volumes:
  traefik_data:
    driver: local
networks:
  traefik_default:
    name: traefik_default
    driver: bridge