global:
  checkNewVersion: false
  sendAnonymousUsage: false

tcpServersTransport:
  tls:
    insecureSkipVerify: true
serversTransport:
  insecureSkipVerify: true # -- (Optional) Change TLS verification here...
# -- (Optional) Change Log Level and Format here...
#     - loglevels [DEBUG, INFO, WARNING, ERROR, CRITICAL]
#     - format [common, json, logfmt]
log:
  level: INFO
  format: common
  filePath: /var/log/traefik/traefik.log

# -- (Optional) Enable Accesslog and change Format here...
#     - format [common, json, logfmt]
accesslog:
  format: common
  filePath: /var/log/traefik/access.log

# -- (Optional) Enable API and Dashboard here, don't do in production
api:
  dashboard: true
  insecure: true

# -- Change EntryPoints here...
entryPoints:
  web:
    address: :80
    # -- (Optional) Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      tls:
        certResolver: production
        domains:
          - main: home.techfitsu.org
            sans:
              - "*.home.techfitsu.org"

  #-- (Optional) Add custom Entrypoint
  #custom:
  #  address: :8080

# -- Configure your CertificateResolver here...
certificatesResolvers:
  staging:
    acme:
      email: alexmtnezf@gmail.com
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /data/traefik/acme.json
      dnsChallenge:
        provider: cloudflare

  production:
    acme:
      email: alexmtnezf@gmail.com
      storage: /data/traefik/acme.json
      dnsChallenge:
        provider: cloudflare

# -- (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem
# -- (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12

providers:
  docker:
    # -- (Optional) Enable this, if you want to expose all containers automatically
    exposedByDefault: false
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    network: traefik_default
  file:
    filename: /etc/traefik/config.yml
