---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-staging-tls
spec:
  secretName: home-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.home.techfitsu.org"
  dnsNames:
  - "*.home.techfitsu.org"